name: first
channels:
    - conda-forge
dependencies:
    - python=3.11
    - numpy
    - pillow
    - opencv
    - scipy
    - pip
    - pip:
        - onnxruntime
        - click
        - setuptools